package.json, src/blockchain/blocks.ts, src/components/nav/ConnectButton.tsx, src/components/nav/NetworkModal.tsx, src/config/tokenMapping.ts, src/contract-wrappers/granda-mento.ts, src/contract-wrappers/sorted-oracles.ts, src/features/accounts/fetchBalances.ts, src/features/blocks/fetchLatestBlock.ts, src/features/chart/PriceChartCelo.tsx, src/features/chart/fetchPrices.ts, src/features/granda/ProposalConfirm.tsx, src/features/granda/ProposalView.tsx, src/features/granda/fetchConfig.ts, src/features/granda/fetchOracleRates.ts, src/features/granda/fetchProposals.ts, src/features/polling/PollingWorker.tsx, src/features/swap/SwapConfirm.tsx, src/features/swap/SwapForm.tsx, src/features/swap/fetchExchangeRates.ts, src/layout/AppLayout.tsx, src/pages/_app.tsx, yarn.lock
replaces @celo-tools/usecontractkit with its successor @celo/react-celo 
adds ContractKit as a direct Dependency (before it was brought in by use-contrackit
=> upgrade to latest @celo/react-celo and contractkit

src/components/input/TokenSelectField.tsx, src/config/tokens.ts, src/features/accounts/fetchBalances.ts, src/features/swap/SwapForm.tsx, src/images/tokens/TokenIcon.tsx
This PR changes the token ID for the specific USDC variant currently supported on Celo main net (axlUSDC) and allows for the specification of additional USDC token variants. 
Additionally, I replaced checks for the USDC token with checks for USDC variants.
I also introduced checks to display the correct list of the available swap tokens based on the connected chain.
Made a change in the TokenIcon component to check for missing token before logic to get specific token icons
axlUSDC is specified everywhere it was previously labelled USDC when connected to Celo main net
When connected to the test networks USDC label is displayed 
When axlUSDC is selected cUSD is automatically selected as the only swap option
Fixes #59 
N/A
N/A
=> fix: Make changes to account for multiple USDC variants

src/features/swap/SwapConfirm.tsx
**Description**
Updates the width of the swap form on mobile to span the width of the screen.
=> fix: use screen width for swap form on xs device

src/features/swap/SwapForm.tsx
This PR is to fix a rounding issue that would break swapping when using the 'use max functionality.' This fix displays the rounded value but swaps the users' max balance (or very close to it using an existing wei conversion function). Users should be able to swap their max balance now. 
N/A
swapped max values for various tokens using a range of amounts 
- Fixes #89 
- [ x ] I have performed a self-review of my own code
=> fix: display rounded max balance, but swap true balance

src/components/input/TokenSelectField.tsx, src/config/exchanges.ts, src/config/tokens.ts, src/features/swap/SwapForm.tsx
This PR adds support for MU03 changes, it also lays the groundwork to make future stable additions more scaleable. The main changes are: 
- axlEUROC has been added
- The exchanges have been updated based on the config produced by the Mento SDK. 
- The token selection validation logic updated to a more scalable solution. Instead of relying on a case-by-case custom validation, the new approach is based on the exchange configuration to check if pairs are swappable. This will ensure greater flexibility and scalability for future changes.
The deployed preview for this branch can be viewed [here](https://mento-8ijde4480-mentolabs.vercel.app/?vercelToolbarCode=msZTvGphOvMZTxJ)
Token outputs are now limited to valid options, only showing users valid options. When a token is selected only the list …
=> feat: add mu03 support

src/config/exchanges.ts, src/config/tokens.ts, src/features/swap/SwapConfirm.tsx, src/features/swap/SwapForm.tsx
This PR adds eXOF support for baklava to allow testing using the UI. 
There's also a fix for error causing the reverse token button to trigger a swap confirm step, by adding 'button' type as it defaults to 'submit'. 
I've set the rate range check to ignore eXOF swaps until we decide if we need them. (If we do the range can be configured on a per pair basis)
I've also set the form values in a single function call in the reverse button as setting them sequentially caused weird quote fetching behaviour. 
I didn't do all the regression test cases, but I did a good few swaps with different currencies and amounts. I did notice there is still rounding issue sometimes when using max, so I've created a issue to capture this, otherwise the quotes and  swaps work as expected. 
- Fixes #91
=> feat:exof support on baklava

src/features/swap/SwapForm.tsx
This PR makes changes to the token list logic to get the main net token list when no wallet is connected
N/A
Checked the token list in the preview version of these changes
- Fixes #issue number here
=> fix: default to mainnet token options when not connected

src/config/exchanges.ts, src/config/tokens.ts
We just ran the eXOF CGP on Alfajores so it can now be added to the frontend. 
Got some Wagmi errors so couldn't run it locally, but I guess this is small enough that it should work?
- Fixes https://github.com/mento-protocol/mento-web/issues/71
=> feat: add eXOF on alfajores

src/layout/AppLayout.tsx
1. Check Markus' video on discord for reproduction https://discord.com/channels/966739027782955068/1065941733260660777/1255081871612575744
1. Reproduce on app.mento.org by making your browser window small enough for the footer to overlap with the token dropdown of the "To:" dropdown
1. See that you can't click the elements that overlap with the footer
1. Check this branch's environment URL and see that the problem is fixed
=> fix: footer had same z-index as <main> and was covering the token dropdown on small screens

src/features/swap/SwapForm.tsx
When Use Max is clicked, it was adding a wrong value to the amount field for tokens with decimals != 18
This PR fixes the issue by passing the correct decimal amount fetched from token config to onClickUseMax
Tested on local and preview
- Fixes https://discord.com/channels/966739027782955068/981497164817637447/1261276291638755348
=> fix: pass token decimals to fromWei

package.json, src/components/nav/Footer.tsx, src/layout/AppLayout.tsx
In a recent change we modified the z index of the main card component. This had an impact on the connect wallet modal meaning the user options such as changing network and disconnect button could not be selected as the modal was now behind the main component. 
This reverts the z index change, then adds some spacing to the footer to enable tokens in the to list to be selectable on short phones.
- None
- Tested in responsive browser
- Fixes https://github.com/mento-protocol/mento-web/issues/137
- [ x] I have performed a self-review of my own code
- [ x] The PR title follows the [conventions](https://www.notion.so/Git-Branching-and-Commit-Message-Conventions-18f66f7d06444cfcbac5725ffbc7c04a?pvs=4#9355048863c549ef92fe210a8a1298aa)
=> refactor: revert z index change + add y-spacing

src/components/nav/ConnectButton.tsx, src/components/nav/NetworkModal.tsx, src/config/wallets.ts
We had an issue where users could not use a safe to execute transactions. This surfaced with a recent bug reported by RefiMedellin(https://discord.com/channels/966739027782955068/1302704425948807179). 
Multiple compounding issues are causing the [bug](https://github.com/mento-protocol/mento-web/issues/150). During investigation and troubleshooting, it was discovered that one of the problems was an invalid WalletConnect state in the local storage (more info [here](https://github.com/orgs/WalletConnect/discussions/3291)).
This change will clear all items in local storage, from wallet connect, when the user connects. This does not fully resolve the bug, as it seems the reported issue is directly related to cCOP/cUSD, but will prevent this specific issue from occurring again.
- None
- …
=> Fix: wallet connect stale storage issue

src/features/swap/SwapForm.tsx, src/features/swap/useSwapQuote.ts, src/utils/amount.ts
One of the utility functions [fromWei()](https://github.com/mento-protocol/mento-web/blob/a391ba4bdd06e4fdf86517d63144590583db2fab/src/utils/amount.ts#L11) was added to convert a value from Wei to a more human-readable format by returning a number. 
The implementation led to precision loss due to the limitations of JavaScript's number type, which can only represent numbers with up to 15-17 significant decimal digits. This was problematic for us as most ERC20 tokens have 18. This caused problems for users if they had a balance like **1122656452787798154** which would have been rounded up in the app resulting in a balance like **1.1226564527877982** which is actually larger than their balance. This would cause their swap to fail if they used the **use max** button instead of just typing an …
=> fix: use max rounding issue

src/features/swap/SwapForm.tsx
_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
This PR addresses an issue where the _Use Max_ button was not displayed for tokens with balances less than 1. The root cause was the use of Number.parseInt() to evaluate token balances, which truncates fractional values, resulting in balances like 0.7 being treated as 0.
**Problem:**
- The Use Max button was visible only when the token balance was greater than or equal to 1.
- Tokens with fractional balances (e.g., 0.5, 0.7) incorrectly failed the check.
- This prevented users from using the _Use Max_ functionality for tokens with balances below 1, potentially impacting usability for large-token-value ecosystems. …
=> fix: ensure 'Use Max' button visibility for token balances > 0

src/utils/amount.ts
Currently, it transforms an amount with >=22 digits to an incorrect amount and proceeds to the confirmation state (e.g., 7478773923223123234925 -> 7.479). The scope is to make it the correct amount with >=22 digits.
None
Put 7478773923223123234925 amount and tried to proceed to confirmation when it exceeded balance
- Fixes #157
=> Fix: Prevented transforming to incorrect amount with >=22 digits

src/features/swap/useFormValidator.ts
the issue discovered by @Andrew718PLTS  https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/mento-web/183
was caused by a bad nearly equal check on the balance that assumed tokens have 18 decimals. That is also why this issue only happened for USDC etc. and not for cUSD.
Since the balance should be strictly gt than the amount I removed the additional condition.
=> fix: remove amounts nearly equal check

package.json, src/config/tokens.ts, src/features/swap/SwapForm.tsx
The form validation was broken because we called the async function `isSwappable` in the filter function without waiting for the promises to be resolved.
This fix ensure only valid token combinations can be selected 
Ensured both multihop and direct broker swaps work, verified only valid pairs can be selected.
=> fix: form validation

src/components/buttons/3DButton.tsx, src/features/swap/SwapConfirm.tsx
It prevents clicking the 'Swap' button on the 'Confirm Swap' state by adding a button disable condition that checks if the txs (approval & swap or swap only) are ready to be confirmed. When it's not ready, the button is disabled and has the grey colour as we do for the 'Continue' button on the 'Swap' state.
Fixed this case:
Sometimes, it shows the 'Sending swap transaction' text when there's no allowance to skip approval tx (therefore, there should be two TXs, approval and swap, and corresponding the 'Sending two transactions: Approval and Swap' text)
**Description:**
There are two cases to test:
1. When there are two txs - an approval and a swap.
2. When there is only one tx - a swap one.
**STR:**
1. Navigate the app and connect your wallet.
3. Fill out the form with any amount.
4. Click …
=> Fix: Prevented clicks on 'Swap' button when it's not ready to send txs

package.json, yarn.lock
There's a delay after pressing the 'Continue' button, that was because of missing using the cache on getting tradable pairs by mento-sdk method. This PR is to update the mento-sdk to a version that contains a fix.
None
1. Navigate to the app
2. Enter a valid amount to any input
3. Click the 'Continue' button
- Fixes #issue number here
=> Fix: Updated mento-sdk with fix to use cache to getTradablePairForTokens to remove delay on navigation to Confirm Swap state

src/components/buttons/3DButton.tsx, src/features/swap/SwapConfirm.tsx, src/features/swap/components/SubmitButton.tsx
After the refactor the swap button has different states with the specified text. Therefore, we can't take this button by particular text anymore, and I added a unique locator.
Made a new enum value for a button text.
Run any swap autotest or check the locator on the Confirm Swap state for the main button.
- Fixes #issue number here
=> Feat: Added locator for confirm swap button

src/features/swap/SwapConfirm.tsx
It prevents infinity swap tx sending on user rejection by adding the `swapRejectedRef` setting when it's been rejected by the user (checking via error message).
**Additionally, to read:**
The `useState` doesn't work in this case because the React state updates asynchronously, so useEffect does not immediately pick up the change in isSwapRejected during the first rejection (that's why I had a case when the first rejection is ignored).
None
Reject when there's an approval and a swap TXs.
1. Select tokens to have an approval TX first (the eXOF would be a good choice).
2. Click the 'Continue' button.
3. Wait until the 'Approve ${token}' button is enabled to click.
4. Click the  'Approve ${token}' button.
5. Approve the approval TX.
6. Reject the swap TX.
Reject when there's no approval TX.
1. …
=> Fix: Prevented infinity swap tx sending on user rejection

src/config/tokens.ts, src/features/accounts/fetchBalances.ts, src/features/polling/PollingWorker.tsx
We couldn't get balances on Alfajores because of the incorrect error handling on getting token balances - it was trying to get the balance of the token with the address that is not correct (cGHS, this way we faced the issue). Now, I replaced it with `try catch` block to prevent throwing an error when there's an issue with some of the tokens. Instead, we load all the tokens we can and display the responsive console error to make it more understandable and prevent problems like this.
Updated address for the 'cGHS' token.
While token/s addresses are correct.
1. Navigate to the preview and connect your wallet where you have tokens on the Alfajores.
2. Change the network to Alfajores.
3. Wait until the balances are loaded.
While token/s addresses are not correct
1. Check out the branch and …
=> Fix: Prevented incorrect error handling on getting token balances and corrected cGHS address for Alfajores

.github/workflows/pr-check.yml
There was a `test` job that was remaining even after the `unit-tests` job is completed (it's been renamed to `unit-tests` in previous PR). Here I just renamed it back to `test`.
None
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
- Fixes #issue number here
=> Fix: Updated pr-check ci job to prevent unused 'test' job

src/features/accounts/fetchBalances.ts
Not sure why this was not done before, but this parallelizes the balance calls by using Promise.all, reducing the initial loading time from 5+ seconds to ~1s.
N/A
Tested it locally to confirm the balances are loaded as expected
=> fix: parallelize balance queries
